### ISSUE TITLE
elm-doc doesn't use indirect deps

### ISSUE THREAD

**Issue by michaelglass** [ento/elm-doc#55]
here's an example app that fails when it has direct and indirect dependencies that use the same namespace

https://gist.github.com/michaelglass/dd3d3db777ac42423f240f73eae04266

`.elm-doc/elm.json` has both indirect & direct deps dumped in the same dependencies hash.

**Comment by ento** [comment]
The issue was that indirect deps shouldn't have been dumped in the same dependencies hash, as package projects don't care for indirect deps. elm-doc converts your project to a package project when generating or validating docs in order to use the official elm binary.

[v1.0.0b4](https://pypi.org/project/elm-doc/1.0.0b4/) has been released with the fix.

Thanks for the MCVE, it was very helpful.
